export const siteConfig = {
  name: "Hikmatullah Hakim - Applied AI Engineer",
  authorName: "Hikmatullah Hakim",
  username: "Hackim7200",
  description:
    "Hikmatullah Hakim - Computer Science (AI) graduate and AWS Certified Cloud Practitioner working across Python, Flutter, React, and cloud infrastructure. Explore my projects, experience, and skills in software development and AI.",
  url: "https://nbarkiya.xyz",
  links: {
    twitter: "https://github.com/Hackim7200",
    github: "https://github.com/Hackim7200",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/profile-img.jpg",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Hikmatullah Hakim",
    "Software Engineer",
    "AI Engineer",
    "Full Stack Developer",
    "Flutter Developer",
    "Python Developer",
    "React Developer",
    "AWS Certified Cloud Practitioner",
    "Machine Learning",
    "Computer Science",
    "Brunel University",
    "Django Developer",
    "TensorFlow",
    "Software Development",
    "Web Developer",
    "Mobile Developer",
    "Tech Portfolio",
  ],
};
